import type { Issue } from "@/components/issue-card";

export const mockIssues: Issue[] = [
  // CRITICAL issues (2)
  {
    id: "1",
    severity: "CRITICAL",
    agent: "secret",
    title: "Hardcoded API key detected in /lib/config.ts",
    filePath: "/lib/config.ts",
    lineNumber: 23,
    codeSnippet: `export const API_KEY = "sk_live_a1b2c3d4e5f6g7h8i9j0";`,
    fixSuggestion: "Move this API key to an environment variable. Use process.env.API_KEY and add the key to your .env.local file.",
  },
  {
    id: "2",
    severity: "CRITICAL",
    agent: "secret",
    title: "Database credentials exposed in source code",
    filePath: "/lib/db.ts",
    lineNumber: 8,
    codeSnippet: `const DB_PASSWORD = "super_secret_password_123!";`,
    fixSuggestion: "Store database credentials in environment variables. Consider using a secrets manager like Vercel's encrypted environment variables.",
  },
  // WARNING issues (3)
  {
    id: "3",
    severity: "WARNING",
    agent: "code",
    title: "Unvalidated user input in SQL query",
    filePath: "/api/users/route.ts",
    lineNumber: 45,
    codeSnippet: `const query = \`SELECT * FROM users WHERE id = '\${userId}'\`;`,
    fixSuggestion: "Use parameterized queries to prevent SQL injection attacks. Consider using an ORM like Prisma or prepared statements.",
  },
  {
    id: "4",
    severity: "WARNING",
    agent: "config",
    title: "Missing Content-Security-Policy header",
    filePath: "/next.config.js",
    lineNumber: 1,
    codeSnippet: `module.exports = {\n  // No security headers configured\n}`,
    fixSuggestion: "Add security headers to your Next.js config. Include Content-Security-Policy, X-Frame-Options, and X-Content-Type-Options.",
  },
  {
    id: "5",
    severity: "WARNING",
    agent: "performance",
    title: "Large unoptimized image detected",
    filePath: "/public/hero-background.png",
    lineNumber: 0,
    codeSnippet: `<!-- 4.2MB PNG file without next/image optimization -->`,
    fixSuggestion: "Use Next.js Image component for automatic optimization, or convert to WebP format and compress the image.",
  },
  // INFO issues (4)
  {
    id: "6",
    severity: "INFO",
    agent: "code",
    title: "Console.log statement found in production code",
    filePath: "/components/dashboard.tsx",
    lineNumber: 67,
    codeSnippet: `console.log("User data:", userData);`,
    fixSuggestion: "Remove console.log statements before deploying to production, or use a proper logging library with log levels.",
  },
  {
    id: "7",
    severity: "INFO",
    agent: "config",
    title: "TypeScript strict mode disabled",
    filePath: "/tsconfig.json",
    lineNumber: 5,
    codeSnippet: `"strict": false`,
    fixSuggestion: "Enable TypeScript strict mode for better type safety. Set \"strict\": true in your tsconfig.json.",
  },
  {
    id: "8",
    severity: "INFO",
    agent: "performance",
    title: "Missing font preloading",
    filePath: "/app/layout.tsx",
    lineNumber: 12,
    codeSnippet: `// Custom fonts loaded without preload hint`,
    fixSuggestion: "Add preload hints for critical fonts to improve First Contentful Paint (FCP).",
  },
  {
    id: "9",
    severity: "INFO",
    agent: "code",
    title: "Deprecated API usage detected",
    filePath: "/lib/analytics.ts",
    lineNumber: 34,
    codeSnippet: `ReactDOM.render(<App />, document.getElementById("root"));`,
    fixSuggestion: "Update to React 18's createRoot API: const root = createRoot(container); root.render(<App />);",
  },
];
